---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.11.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['admin@example.com']
        nginx['redirect_http_to_https'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['time_zone'] = 'Tehran'
        gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '/srv/gitlab-docker/config:/etc/gitlab'
      - '/srv/gitlab-docker/logs:/var/log/gitlab'
      - '/srv/gitlab-docker/data:/var/opt/gitlab'
      - '/srv/gitlab-docker/backups:/var/opt/gitlab/backups'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
...
